const mockUser = {
  login: "web-galtsov",
  id: 68854681,
  node_id: "MDQ6VXNlcjY4ODU0Njgx",
  avatar_url: "https://avatars.githubusercontent.com/u/68854681?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/web-galtsov",
  html_url: "https://github.com/web-galtsov",
  followers_url: "https://api.github.com/users/web-galtsov/followers",
  following_url: "https://api.github.com/users/web-galtsov/following{/other_user}",
  gists_url: "https://api.github.com/users/web-galtsov/gists{/gist_id}",
  starred_url: "https://api.github.com/users/web-galtsov/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/web-galtsov/subscriptions",
  organizations_url: "https://api.github.com/users/web-galtsov/orgs",
  repos_url: "https://api.github.com/users/web-galtsov/repos",
  events_url: "https://api.github.com/users/web-galtsov/events{/privacy}",
  received_events_url: "https://api.github.com/users/web-galtsov/received_events",
  type: "User",
  site_admin: false,
  name: "WebStudio",
  company: null,
  blog: "https://www.webworkoxana.com/",
  location: "bat-yam Israel",
  email: null,
  hireable: null,
  bio: "הי, אני אוקסנה. יש לי ניסיון מסחרי של 10 שנים ביצירת אתרים מצליחים אשר מעוצבים ונבנים בהתחשב עם הביצועים ושיטות העבודה המומלצות בראש.",
  twitter_username: null,
  public_repos: 25,
  public_gists: 0,
  followers: 0,
  following: 0,
  created_at: "2020-07-27T12:18:10Z",
  updated_at: "2022-01-17T20:09:03Z"
};
export default mockUser